import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
import SessionWrapProvider from "@/app/session-provider";

// const inter = Inter({ subsets: ["latin"] });

const nunito = Nunito({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${nunito.className} text-primary !scroll-smooth`}>
        <Toaster />
        <SessionWrapProvider>
          {children}
        </SessionWrapProvider>
      </body>
    </html>
  );
}
